import Head from 'next/head'
import { gsap } from 'gsap';
import { useEffect } from 'react';
import circle from "../public/Rectangle.png"
import Image from 'next/image';
import mobileBackground from '../public/mobileBackground.png'
import join from "../public/join.png"
export default function Home() {

  useEffect(() => {
    // setTimeout(() => {
    gsap.to('.main', {
      duration: 2,
      opacity: 1,
      ease: "sine.out",
    })
    // }, 1000)
  }, []);


  return (
    <>
      <Head>
        <title>Join Beta</title>
        <link rel="preload" as="image" href="https://skies.netlify.app/_next/static/media/cloud2.44e789a9.webp" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
      <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600;700&display=swap" rel="stylesheet"></link>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
      <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main bg-black px-4 min-h-[100vh]'>
        <div className='w-full flex flex-col relative'>
        <Image unoptimized={true} className='h-[200px]  shadow-xl -translate-y-20 m-auto w-auto background-bottom-right'alt="gradient circle" src={circle}></Image>
        <h1 className='title absolute top-[150px] max-w-[800px]  flex justify-center z-10 text-white font-semibold text-3xl md:text-6xl text-center'>Focus on Your Craft. Leave the Rest to Us.</h1>
        <Image unoptimized={true} className="md:hidden absolute shadow-xl mobile-waffle  h-[600px] md:h-[800px] top-0 opacity-50 -translate-x-[50%]  translate-y-24 md:translate-y-8" src={mobileBackground} alt="waffle for background"/>
        <div className="absolute waffle-shadow -translate-x-[60%] inset-0 h-[600px] md:h-[800px] top-0  rounded-lg bg-white-shadow opacity-75"></div>
        <div className="absolute circle-shadow  md:hidden  top-[0] md:top-[0%] inset-0 h-[300px] md:h-[500px] top-0  rounded-lg bg-white-shadow opacity-75"></div>
        <p className='font-Raleway text-white mid-content text-justify text-center top-[200px] flex justify-center'>Unleash the power of your art. Monetize, build your brand and connect with collectors.</p>
        <a href="https://twitter.com" className='flex w-full justify-center'><Image className='top-[400px] absolute w-[200px]'alt="join beta button" src={join}></Image></a>
        </div>
      </main>

    </>
  )
}
